spectrum_reader : spectrum_reader.c tsvlib/tsvlib.h tsvlib/tsvlib.o
	gcc -Wall -g spectrum_reader.c tsvlib/tsvlib.o -o spectrum_reader

tsvlib/tsvlib.o : tsvlib/tsvlib.c tsvlib/tsvlib.h
	gcc -Wall -c -g tsvlib/tsvlib.c -o tsvlib/tsvlib.o
